<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>default</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Desktop.Robot" Version="1.5.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10"/>
        <PackageReference Include="Serilog" Version="4.3.0"/>
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Menagerie.Core.Linux\Menagerie.Core.Linux.csproj"/>
        <ProjectReference Include="..\Menagerie.Core.Windows\Menagerie.Core.Windows.csproj"/>
    </ItemGroup>

</Project>
